server:
  tomcat:
    uri-encoding: UTF-8
  port: 8100

spring:
  datasource:
    name: datasource
    url: jdbc:mysql://127.0.0.1:3306/db_gwol?characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
#  profiles:
#    active: ${config.profile:dev}
  application:
    name: gwpz
  aop:
    auto: true
    proxy-target-class: true
  freemarker:
    request-context-attribute: request
    suffix: '.ftl'
    content-type: text/html
    enabled: true
    cache: false
    template-loader-path: classpath:/pages/
    charset: UTF-8
    settings:
      number_format: '0.##'   #数字格式化，无小数点
#  resources:
#    static-locations: classpath:/**

mybatis:
    type-aliases-package: org.europeguy.entity
    mapper-locations: org.europeguy.mapper/*.xml
    
mapper:
    not-empty: false
    identity: MYSQL

logging:
  config: classpath:logback-spring.xml

auto_import:  "/component/global.ftl as global"
auto_include: _