server:
  tomcat:
    uri-encoding: UTF-8 

spring:
  profiles:
    active: ${config.profile:dev}
  application:
    name: gwpz
  aop:
    auto: true
    proxy-target-class: true
  freemarker:
    request-context-attribute: request
    suffix: '.ftl'
    content-type: text/html
    enabled: true
    cache: false
    template-loader-path: classpath:/pages/
    charset: UTF-8
    settings:
      number_format: '0.##'   #数字格式化，无小数点

mybatis:
    type-aliases-package: org.europeguy.entity
    mapper-locations: org.europeguy.mapper/*.xml
    
mapper:
    not-empty: false
    identity: MYSQL

pagehelper:
    offsetAsPageNum: true
    rowBoundsWithCount: true
    reasonable: true
    supportMethodsArguments: true
    closeConn: false
      
logging:
  config: classpath:logback-spring.xml
  
manager:
  username: admin
  passwd: admin
  
auto_import:  "/component/global.ftl as global"
auto_include: _